# Dockerfile pour MinIO
FROM minio/minio:latest

# Crée le répertoire de données
RUN mkdir -p /data

# Expose les ports MinIO
EXPOSE 9000 9001

# Point d'entrée MinIO
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
CMD ["minio", "server", "/data", "--console-address", ":9001"]
